import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';

async function login(page: Page, username: string) {
  await page.goto('/');
  await page.getByLabel('账号', { exact: true }).fill(username);
  await page.getByLabel('密码', { exact: true }).fill('TestOnlyE2e-2026');
  await page.getByRole('button', { name: '进入工作空间' }).click();
  await expect(page.getByRole('button', { name: '退出', exact: true })).toBeVisible();
}

async function createDraft(page: Page, title: string) {
  await page.getByRole('link', { name: '提醒任务', exact: true }).click();
  await page.getByRole('link', { name: '创建提醒', exact: true }).click();
  await page.getByLabel('演示一局', { exact: true }).check();
  await page.getByRole('button', { name: '预览接收名单', exact: true }).click();
  await expect(page.getByRole('heading', { name: '名单预览：16 人' })).toBeVisible();
  await page.getByRole('button', { name: '2. 编辑内容', exact: true }).click();
  await page.getByLabel('提醒标题', { exact: true }).fill(title);
  await page.getByRole('textbox', { name: '提醒正文', exact: true }).fill('请严格执行岗位纪律，依规履职。');
  await page.getByRole('button', { name: '4. 保存核对', exact: true }).click();
  await page.getByRole('button', { name: '保存草稿并核对', exact: true }).click();
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await expect(page.getByText('请严格执行岗位纪律，依规履职。', { exact: true })).toBeVisible();
}

async function confirmAndSubmit(page: Page) {
  await page.getByRole('checkbox', { name: /我已核对最终内容/ }).check();
  await page.getByRole('button', { name: '确认名单与内容', exact: true }).click();
  await expect(page.getByRole('button', { name: '提交审核', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '提交审核', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '确认操作', exact: true }).click();
  await expect(page.getByText('第 1 轮审核 · 待审核内容和名单为冻结快照。', { exact: true })).toBeVisible();
}

test('unit creator freezes a task, an independent reviewer approves it, and Mock delivery preserves the roster', async ({ page }, testInfo) => {
  const title = '浏览器独立审核提醒';
  await login(page, 'unit');
  await createDraft(page, title);
  await confirmAndSubmit(page);
  await expect(page.getByRole('button', { name: '审核通过', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录明镜' })).toBeVisible();
  await login(page, 'reviewer');
  await page.getByRole('link', { name: '审核工作台', exact: true }).click();
  await page.getByRole('link', { name: title, exact: true }).click();
  await expect(page.getByRole('heading', { name: '最终内容预览', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: '编辑草稿', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '审核通过', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '确认操作', exact: true }).click();
  await expect(page.getByText(/审核已通过，发送作业已排队/)).toBeVisible();
  await page.reload();
  await expect(page.getByText(/审核已通过，发送作业已排队/)).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('review-approved.png'), fullPage: true });
  const taskUrl = page.url();
  await expect(page.getByRole('button', { name: '执行 Mock 发送', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录明镜' })).toBeVisible();
  await login(page, 'unit');
  await page.goto(taskUrl);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '执行 Mock 发送', exact: true }).click();
  const delivery = page.getByRole('region', { name: '送达与阅读结果' });
  await expect(delivery.getByText('Mock 演示渠道', { exact: false })).toBeVisible();
  await expect(delivery.getByText(/目标 16 人 · 已送达 16 人/)).toBeVisible();
  await expect(delivery.getByRole('cell', { name: '未读', exact: true })).toHaveCount(16);
  await expect(delivery.getByRole('button', { name: '执行 Mock 发送', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(delivery.getByText(/目标 16 人 · 已送达 16 人/)).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('mock-delivery-results.png'), fullPage: true });
  const popup = page.waitForEvent('popup');
  await delivery.getByRole('button', { name: '演示人员01 的本人阅读演示', exact: true }).click();
  const receiver = await popup;
  await receiver.setViewportSize({ width: 390, height: 844 });
  await expect(receiver.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await expect(receiver.getByText(/已记录本版本首次阅读/)).toBeVisible();
  await expect(receiver.getByText('本提醒仅向本人展示，请勿截图外传。', { exact: true })).toBeVisible();
  await expect(receiver.getByRole('link', { name: '人员与组织', exact: true })).toHaveCount(0);
  const firstRead = await receiver.getByText(/已记录本版本首次阅读/).textContent();
  await receiver.reload();
  await expect(receiver.getByText(/已记录本版本首次阅读/)).toHaveText(firstRead!);
  await receiver.screenshot({ path: testInfo.outputPath('receiver-mobile.png'), fullPage: true });
  await receiver.close();
  await delivery.getByRole('button', { name: '刷新结果', exact: true }).click();
  await expect(delivery.getByText(/最新版本已读 1 人/)).toBeVisible();
  await page.getByRole('link', { name: '阅读与逾期', exact: true }).click();
  await expect(page.getByRole('heading', { name: '阅读与逾期', exact: true })).toBeVisible();
  await page.getByLabel('姓名或当前单位', { exact: true }).fill('演示人员01');
  await expect(page.getByRole('row').filter({ hasText: title })).toHaveCount(0);
  await page.getByRole('combobox', { name: '状态', exact: true }).selectOption('OVERDUE');
  await expect(page.getByText('当前条件下没有未读提醒。', { exact: true })).toBeVisible();
  await page.goto(taskUrl);
  const taskId = taskUrl.split('/').at(-1)!;
  const originalDelivery = await (await page.request.get(`/api/reminders/${taskId}/delivery`)).json();
  await page.getByRole('link', { name: '修订内容', exact: true }).click();
  await page.getByLabel('修订标题', { exact: true }).fill('浏览器修订后的提醒');
  await page.getByRole('textbox', { name: '提醒正文', exact: true }).fill('这是经过再次审核的新版本，请核对最新内容。');
  await page.getByRole('button', { name: '保存修订并核对', exact: true }).click();
  await page.getByRole('checkbox', { name: /我已核对本次修订/ }).check();
  await page.getByRole('button', { name: '确认修订内容', exact: true }).click();
  await expect(page.getByRole('button', { name: '提交修订审核', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '提交修订审核', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '确认操作', exact: true }).click();
  await expect(page.getByText(/修订待审核 · 审核发布前/)).toBeVisible();
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录明镜' })).toBeVisible();
  await login(page, 'reviewer');
  await page.getByRole('link', { name: '审核工作台', exact: true }).click();
  await page.getByRole('link', { name: title, exact: true }).click();
  await expect(page.getByRole('heading', { name: '浏览器修订后的提醒', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '审核通过', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '确认操作', exact: true }).click();
  await expect(page.getByText(/修订待审核 · 审核发布前/)).toHaveCount(0);
  await page.getByRole('button', { name: '退出', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登录明镜' })).toBeVisible();
  await login(page, 'unit');
  await page.goto(taskUrl);
  await expect(page.getByRole('heading', { name: '浏览器修订后的提醒', exact: true })).toBeVisible();
  await expect(delivery.getByText(/最新版本已读 0 人/)).toBeVisible();
  const revisedDelivery = await (await page.request.get(`/api/reminders/${taskId}/delivery`)).json();
  expect(revisedDelivery.recipients.map((r: { id: string; deadlineAt: string }) => [r.id, r.deadlineAt]))
    .toEqual(originalDelivery.recipients.map((r: { id: string; deadlineAt: string }) => [r.id, r.deadlineAt]));
  const revisedPopup = page.waitForEvent('popup');
  await delivery.getByRole('button', { name: '演示人员01 的本人阅读演示', exact: true }).click();
  const revisedReceiver = await revisedPopup;
  await expect(revisedReceiver.getByRole('heading', { name: '浏览器修订后的提醒', exact: true })).toBeVisible();
  await expect(revisedReceiver.getByText(/已记录本版本首次阅读/)).toBeVisible();
  await revisedReceiver.setViewportSize({ width: 390, height: 844 });
  await revisedReceiver.screenshot({ path: testInfo.outputPath('revision-receiver.png'), fullPage: true });
  await delivery.getByRole('checkbox', { name: '选择撤回 演示人员01', exact: true }).check();
  await delivery.getByRole('button', { name: '撤回所选 1 人', exact: true }).click();
  await page.getByRole('dialog').getByLabel('撤回原因', { exact: true }).fill('浏览器逐人撤回验证');
  await page.getByRole('button', { name: '确认提交撤回', exact: true }).click();
  await expect(page.getByText(/部分撤回 · 创建单位/)).toBeVisible();
  await expect(delivery.getByRole('cell', { name: '已撤回', exact: true })).toHaveCount(1);
  await revisedReceiver.reload();
  await expect(revisedReceiver.getByText('本提醒已撤回', { exact: true })).toBeVisible();
  await expect(revisedReceiver.getByText('这是经过再次审核的新版本，请核对最新内容。', { exact: true })).toHaveCount(0);
  await revisedReceiver.screenshot({ path: testInfo.outputPath('withdrawn-receiver.png'), fullPage: true });
  await revisedReceiver.close();
  await delivery.getByRole('button', { name: '选择全部未申请人员', exact: true }).click();
  await delivery.getByRole('button', { name: '撤回所选 15 人', exact: true }).click();
  await page.getByRole('dialog').getByLabel('撤回原因', { exact: true }).fill('撤回剩余人员验证');
  await page.getByRole('button', { name: '确认提交撤回', exact: true }).click();
  await expect(page.getByText(/全部撤回 · 创建单位/)).toBeVisible();
  await expect(delivery.getByRole('cell', { name: '已撤回', exact: true })).toHaveCount(16);
  await delivery.getByRole('button', { name: '查看撤回记录', exact: true }).click();
  await expect(delivery.getByRole('heading', { name: '撤回记录', exact: true })).toBeVisible();
  await expect(delivery.getByText('浏览器逐人撤回验证', { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('withdrawal-results.png'), fullPage: true });
  await page.goto('/dashboard');
  await page.getByRole('combobox', { name: '提醒任务', exact: true }).selectOption(taskId);
  await page.getByRole('button', { name: '应用筛选', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看提醒目标明细', exact: true }).locator('strong')).toHaveText('16');
  await expect(page.getByRole('button', { name: '查看送达者最新版本阅读率明细', exact: true }).locator('strong')).toHaveText('6.3%');
  await page.getByRole('button', { name: '查看提醒目标明细', exact: true }).click();
  await expect(page.getByText('明细共 16 条', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭明细', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('reminder-business-dashboard.png'), fullPage: true });
  await page.getByRole('combobox', { name: '提醒历史范围', exact: true }).selectOption('false');
  await page.getByRole('button', { name: '应用筛选', exact: true }).click();
  await expect(page.getByRole('button', { name: '查看提醒目标明细', exact: true }).locator('strong')).toHaveText('0');
  await expect(page.getByRole('button', { name: '查看送达者最新版本阅读率明细', exact: true }).locator('strong')).toHaveText('—');
});

test('draft edits invalidate confirmation and explicit exclusion survives a saved edit', async ({ page }) => {
  await login(page, 'unit');
  await createDraft(page, '浏览器编辑名单提醒');
  await page.getByRole('checkbox', { name: /我已核对最终内容/ }).check();
  await page.getByRole('button', { name: '确认名单与内容', exact: true }).click();
  await expect(page.getByRole('button', { name: '提交审核', exact: true })).toBeEnabled();
  await page.getByRole('link', { name: '编辑草稿', exact: true }).click();
  await page.getByRole('button', { name: '移除 演示人员01', exact: true }).click();
  await page.getByRole('button', { name: '重新预览', exact: true }).click();
  await expect(page.getByRole('heading', { name: '名单预览：15 人' })).toBeVisible();
  await page.getByRole('button', { name: '4. 保存核对', exact: true }).click();
  await page.getByRole('button', { name: '保存草稿并核对', exact: true }).click();
  await expect(page.getByRole('button', { name: '提交审核', exact: true })).toBeDisabled();
  await expect(page.getByText('手工排除', { exact: true })).toBeVisible();
});
