import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { dashboardMock } from './dashboardMock';
import type { DashboardPerson } from './dashboardMock';

type Drilldown = { title: string; description: string; people: DashboardPerson[] } | null;

const metricAccent: Record<string, string> = {
  blue: 'before:bg-blue-400', violet: 'before:bg-violet-400', cyan: 'before:bg-cyan-400', emerald: 'before:bg-emerald-400',
};
const organizationAccent: Record<string, string> = {
  blue: 'bg-blue-400', cyan: 'bg-cyan-400', violet: 'bg-violet-400', amber: 'bg-amber-400',
};
const qualityAccent: Record<string, string> = {
  rose: 'bg-rose-400/10 text-rose-300', amber: 'bg-amber-400/10 text-amber-300', violet: 'bg-violet-400/10 text-violet-300', slate: 'bg-slate-400/10 text-slate-300',
};

export function Dashboard() {
  const data = dashboardMock;
  const mode = new URLSearchParams(window.location.search).get('state');
  const [loading, setLoading] = useState(true);
  const [drilldown, setDrilldown] = useState<Drilldown>(null);
  const open = (title: string, description: string, people = data.overduePeople) => setDrilldown({ title, description, people });
  useEffect(() => {
    if (mode === 'loading') return;
    const timer = window.setTimeout(() => setLoading(false), 120);
    return () => window.clearTimeout(timer);
  }, [mode]);
  if (loading || mode === 'loading') return <DashboardState title="正在加载核心价值数据" description="正在汇总对象、标签和提醒闭环指标…" />;
  if (mode === 'empty') return <DashboardState title="当前统计范围暂无数据" description="调整组织范围或统计时间后重新加载。演示页面保留空数据状态供原型验收。" empty />;
  return <div className="dashboard-shell min-h-[calc(100vh-8rem)] overflow-x-hidden bg-[#07111f] p-5 text-slate-100 lg:p-9">
    <header className="flex flex-wrap items-end justify-between gap-6">
      <div><p className="text-xs font-semibold tracking-[0.32em] text-cyan-300">MIRROR · OBJECT LIBRARY</p><h1 className="mt-3 text-3xl font-semibold tracking-tight lg:text-4xl">政务系统对象库 · 核心价值总览</h1><p className="mt-3 text-sm text-slate-400">对象 · 关系 · 画像 · 提醒 · 闭环</p></div>
      <div className="flex items-center gap-3 text-right text-xs text-slate-400"><span className="rounded-full border border-amber-400/40 bg-amber-400/10 px-3 py-1.5 font-medium text-amber-200">演示数据 / Mock</span><span>统计时间<br /><strong className="font-medium text-slate-200">{data.generatedAt}</strong></span></div>
    </header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="有效对象" value={data.overview.validObjects.toLocaleString()} detail="全市有效人员去重" color="blue" /><Metric label="标签覆盖率" value={`${data.overview.tagCoverage}%`} detail={`${data.overview.taggedObjects.toLocaleString()} 人已有当前标签`} color="violet" /><Metric label="活跃提醒任务" value={data.overview.activeReminders} detail="当前周期已发布任务" color="cyan" /><Metric label="最新版本阅读率" value={`${data.overview.readRate}%`} detail={`${data.overview.read.toLocaleString()} / ${data.overview.delivered.toLocaleString()} 已送达`} color="emerald" />
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
      <Panel title="对象与组织" eyebrow="01 · OBJECTS & RELATIONSHIPS" action="查看对象明细" onClick={() => open('对象与组织明细', '演示当前组织范围内的对象摘要。')}><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-4">{data.organizations.map(item => <button key={item.name} onClick={() => open(item.name, '演示组织下的对象摘要。', data.overduePeople.filter(p => p.organization === item.name))} className="flex w-full items-center gap-3 text-left"><span className={`h-2.5 w-2.5 rounded-full ${organizationAccent[item.color]}`} /><span className="w-28 text-sm text-slate-300">{item.name}</span><span className="h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><span className={`block h-full rounded-full ${organizationAccent[item.color]}`} style={{ width: `${item.share * 2.2}%` }} /></span><span className="w-20 text-right text-sm tabular-nums text-slate-200">{item.count.toLocaleString()}</span></button>)}</div><div className="rounded-xl border border-slate-700/60 bg-slate-900/50 p-5"><p className="text-xs text-slate-400">对象数据质量</p><div className="mt-4 flex items-center gap-5"><div className="grid h-28 w-28 shrink-0 place-items-center rounded-full" style={{ background: 'conic-gradient(#22d3ee 0 95%, #334155 95% 100%)' }}><div className="grid h-20 w-20 place-items-center rounded-full bg-slate-900"><strong className="text-2xl">99.1%</strong></div></div><p className="text-xs leading-6 text-slate-400">对象保留在库内，关联异常进入治理清单。</p></div></div></div></Panel>
      <Panel title="标签画像" eyebrow="02 · TAGGED PORTRAIT" action="查看标签明细" onClick={() => open('重点标签覆盖人员', '演示标签排行对应的人员入口。')}><div className="flex gap-6"><div className="grid h-36 w-36 shrink-0 place-items-center rounded-full" style={{ background: 'conic-gradient(#8b5cf6 0 58%, #14b8a6 58% 78%, #f59e0b 78% 91%, #334155 91% 100%)' }}><div className="grid h-24 w-24 place-items-center rounded-full bg-slate-900 text-center"><strong className="text-2xl">95.4%</strong><span className="text-[10px] text-slate-400">已形成画像</span></div></div><div className="min-w-0 flex-1 space-y-3">{data.tags.map(tag => <button key={tag.name} onClick={() => open(tag.name, '演示标签覆盖人员。')} className="flex w-full items-center gap-3 text-left text-xs"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: tag.color }} /><span className="min-w-0 flex-1 truncate text-slate-300">{tag.name}</span><strong className="tabular-nums text-slate-100">{tag.count.toLocaleString()}</strong></button>)}</div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-lg bg-violet-400/10 p-3"><p className="text-xs text-violet-200">长期性标签</p><strong className="mt-1 block text-xl">42,180</strong></div><div className="rounded-lg bg-amber-400/10 p-3"><p className="text-xs text-amber-200">阶段性标签</p><strong className="mt-1 block text-xl">8,640</strong></div></div></Panel>
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><Panel title="提醒闭环" eyebrow="03 · REMINDER LOOP" action="查看逾期人员" onClick={() => open('逾期未读人员', '超过个人阅读时限且当前版本仍未阅读。')}><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-4">{data.reminderFunnel.map(item => <button key={item.label} onClick={() => item.label === '逾期未读' && open(item.label, '超过个人阅读时限且当前版本仍未阅读。')} className="flex w-full items-center gap-3 text-left"><span className="w-20 text-xs text-slate-400">{item.label}</span><span className="h-3 flex-1 overflow-hidden rounded-full bg-slate-800"><span className={`block h-full rounded-full ${item.color}`} style={{ width: `${Math.max(item.value / 34820 * 100, 2)}%` }} /></span><strong className="w-16 text-right text-sm tabular-nums">{item.value.toLocaleString()}</strong></button>)}</div><div className="rounded-xl border border-slate-700/60 bg-slate-900/50 p-4"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">近7日阅读趋势</span><span className="text-xs text-emerald-300">+12.4%</span></div><div className="mt-5 flex h-28 items-end gap-2">{data.trend.map((value, index) => <div key={index} className="group flex flex-1 flex-col items-center gap-2"><span className="w-full rounded-t bg-cyan-400/80" style={{ height: `${value}%` }} /><span className="text-[10px] text-slate-500">{index === 6 ? '今' : `-${6 - index}`}</span></div>)}</div></div></div></Panel><Panel title="数据质量" eyebrow="04 · DATA QUALITY"><div className="space-y-3">{data.quality.map(item => <button key={item.label} onClick={() => open(item.label, item.hint)} className="flex w-full items-center gap-3 rounded-lg border border-slate-700/60 bg-slate-900/40 p-3 text-left"><span className={`grid h-9 w-9 place-items-center rounded-lg text-sm ${qualityAccent[item.tone]}`}>!</span><span className="min-w-0 flex-1"><strong className="block text-xs text-slate-200">{item.label}</strong><small className="mt-1 block truncate text-[11px] text-slate-500">{item.hint}</small></span><strong className="text-lg tabular-nums text-slate-100">{item.value}</strong></button>)}</div></Panel></section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-slate-700/60 bg-slate-900/70"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700/60 px-5 py-4"><div><p className="text-[10px] font-semibold tracking-[0.2em] text-slate-500">05 · TRACEABLE OPERATIONS</p><h2 className="mt-1 font-medium">最近提醒任务</h2></div><span className="text-xs text-slate-500">点击上方指标可查看演示下钻</span></div><div className="overflow-x-auto"><table className="w-full min-w-[620px]"><thead><tr className="text-left text-xs text-slate-500"><th className="px-5 py-3 font-normal">任务</th><th className="px-5 py-3 font-normal">创建组织</th><th className="px-5 py-3 font-normal">目标人数</th><th className="px-5 py-3 font-normal">最新版本已读</th><th className="px-5 py-3 font-normal">状态</th></tr></thead><tbody>{data.recentTasks.map(task => <tr key={task.title} className="border-t border-slate-800 text-sm"><td className="px-5 py-4 font-medium text-slate-200">{task.title}</td><td className="px-5 py-4 text-slate-400">{task.organization}</td><td className="px-5 py-4 tabular-nums text-slate-300">{task.target.toLocaleString()}</td><td className="px-5 py-4 tabular-nums text-cyan-300">{task.read.toLocaleString()}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs text-emerald-300">{task.state}</span></td></tr>)}</tbody></table></div></section>
    {drilldown && <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/70 p-5" role="presentation" onClick={() => setDrilldown(null)}><section className="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6 shadow-2xl" role="dialog" aria-modal="true" aria-label={drilldown.title} onClick={event => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs tracking-widest text-cyan-300">演示下钻</p><h2 className="mt-2 text-xl font-semibold">{drilldown.title}</h2><p className="mt-2 text-sm text-slate-400">{drilldown.description}</p></div><button className="text-slate-400 hover:text-white" onClick={() => setDrilldown(null)} aria-label="关闭">×</button></div>{drilldown.people.length === 0 ? <p className="mt-6 rounded-lg bg-slate-800 p-4 text-sm text-slate-400">当前 Mock 范围没有明细。</p> : <div className="mt-6 divide-y divide-slate-800">{drilldown.people.map(person => <div className="flex items-center justify-between py-3" key={`${person.name}-${person.organization}`}><div><p className="text-sm text-slate-200">{person.name}</p><p className="mt-1 text-xs text-slate-500">{person.organization} · {person.tag}</p></div><span className="text-xs text-rose-300">{person.state}</span></div>)}</div>}<p className="mt-6 text-[11px] text-slate-500">Mock 明细仅用于展示从指标回到对象的业务路径。</p></section></div>}
  </div>;
}

function DashboardState({ title, description, empty = false }: { title: string; description: string; empty?: boolean }) {
  return <div className="dashboard-shell grid min-h-[calc(100vh-8rem)] place-items-center overflow-x-hidden bg-[#07111f] p-5 text-slate-100 lg:p-9"><div className="w-full max-w-lg rounded-2xl border border-slate-700/60 bg-slate-900/80 p-8 text-center" role="status"><span className={`mx-auto grid h-12 w-12 place-items-center rounded-full ${empty ? 'bg-slate-700 text-slate-300' : 'bg-cyan-400/10 text-cyan-300'}`}>{empty ? '—' : '…'}</span><h1 className="mt-5 text-xl font-semibold">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><p className="mt-6 text-xs text-amber-200">演示数据 / Mock</p></div></div>;
}

function Metric({ label, value, detail, color }: { label: string; value: string | number; detail: string; color: string }) {
  return <div className={`relative overflow-hidden rounded-xl border border-slate-700/60 bg-slate-900/70 p-5 before:absolute before:inset-x-0 before:top-0 before:h-0.5 ${metricAccent[color]}`}><p className="text-xs text-slate-400">{label}</p><strong className="mt-3 block text-3xl font-semibold tracking-tight">{value}</strong><p className="mt-2 text-xs text-slate-500">{detail}</p></div>;
}

function Panel({ title, eyebrow, action, onClick, children }: { title: string; eyebrow: string; action?: string; onClick?: () => void; children: ReactNode }) {
  return <section className="panel border-slate-700/60 bg-slate-900/70 p-5"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold tracking-[0.2em] text-slate-500">{eyebrow}</p><h2 className="mt-1 font-medium">{title}</h2></div>{action && <button className="text-xs text-cyan-300 hover:text-cyan-200" onClick={onClick}>{action} →</button>}</div>{children}</section>;
}
